name: persolette
options:
  bundleIdPrefix: com.hicham.persolette
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
targets:
  persolette:
    type: application
    platform: iOS
    sources:
      - path: persolette
    info:
      path: persolette/Info.plist
      properties:
        CFBundleDisplayName: persolette
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hicham.persolette
        PRODUCT_NAME: persolette
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_PREVIEWS: YES
        IPHONEOS_DEPLOYMENT_TARGET: "16.0"
schemes:
  persolette:
    build:
      targets:
        persolette: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
